### ISSUE TITLE
Fehler in Aufgabe 4 

### ISSUE THREAD

**Issue by mircb** [mircb/AbgabeAufgaben#1]
Fehler:

java.io.StreamCorruptedException: invalid type code: AC
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1381)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at listerner.run(listerner.java:31)

**Comment by mayrmartin** [comment]
fixed in last commit

**Comment by mircb** [comment]
very much helpfull thanxs. can close issues now !
